BEGIN;

UPDATE auth.users SET encrypted_password = '$firebase$scrypt$v=1,p=C34xz4ekGPX5iZlzLDe+LmWIFePZi+7ncRYs4sgmucs=,s=Bw==,r=8,m=14$Tpn5yPDDUvAg+w==$7AFwE6wkF4m3ayBTB3XiJkPd8foJSJPGdpxIIOFYUvRfFGOUMh4Kd035xfZene+BehaB5WiRF2j973o1p56KtA==' WHERE email = 'maguitonajera78@gmail.com';
UPDATE auth.users SET encrypted_password = '$firebase$scrypt$v=1,p=C34xz4ekGPX5iZlzLDe+LmWIFePZi+7ncRYs4sgmucs=,s=Bw==,r=8,m=14$YmzHT+QxXe1p0A==$B5/vKEFiqaV5V+Iz+kxI7wlT2nolYKf0c+HslakGoTjztlXSHoCnevej81scsxggCVamWBtZkF7BqnaV/BKfaw==' WHERE email = 'williamsmendez1810@gmail.com';
UPDATE auth.users SET encrypted_password = '$firebase$scrypt$v=1,p=C34xz4ekGPX5iZlzLDe+LmWIFePZi+7ncRYs4sgmucs=,s=Bw==,r=8,m=14$9pKgvuRBoOcitQ==$MHuTDXoRJoOHYzRXPUgujhX/Q8xFNDFK/owt3GmGpeASd7vBpQkOuzbglsW2YHrDsg7kSjra2SkP/79VlghaAQ==' WHERE email = 'yuzeberecruzmoreno@gmail.com';
UPDATE auth.users SET encrypted_password = '$firebase$scrypt$v=1,p=C34xz4ekGPX5iZlzLDe+LmWIFePZi+7ncRYs4sgmucs=,s=Bw==,r=8,m=14$RWJLEsZ0cFY2Ag==$TBMuH0/uHgBNytnaDmm6b2fbDRmWS7fIAGRW7FNTJqJlvrE53bz3fDg+EDuBRnTrY9jszpdEtkXyKdnhtWExZQ==' WHERE email = 'carlosalbertorangellopez114@gmail.com';
UPDATE auth.users SET encrypted_password = '$firebase$scrypt$v=1,p=C34xz4ekGPX5iZlzLDe+LmWIFePZi+7ncRYs4sgmucs=,s=Bw==,r=8,m=14$1BSPh0yqJiSuYA==$O+XGBW3KxXEnb3VG/Yw8T7cDwsZ1JqRsP9cGb7PHbeIW7eeoNoW7hLonZoFGV35tmBPrwuHjcy2cnyrFeI+elA==' WHERE email = 'rf.zambrano1236@gmail.com';
UPDATE auth.users SET encrypted_password = '$firebase$scrypt$v=1,p=C34xz4ekGPX5iZlzLDe+LmWIFePZi+7ncRYs4sgmucs=,s=Bw==,r=8,m=14$BuL+d+kSPyelpQ==$K1xTmeld46OXNBAhYG1fhn67y+JpdKZiFbXV4OV7WxT50ygHZD+d3EAlZ4/00qZPav74eBNSWf6CC5EIvHnuBA==' WHERE email = 'ale.loza.c@outlook.com';
UPDATE auth.users SET encrypted_password = '$firebase$scrypt$v=1,p=C34xz4ekGPX5iZlzLDe+LmWIFePZi+7ncRYs4sgmucs=,s=Bw==,r=8,m=14$aUEAVE2cCAsrgw==$0ahMHh6GQrryxoA1iHad/r4oQigZrSCjtxhbaV2VrMJ10jtvGT2NWM425uVlnGraD8HunXPiS6OkpoQRaNkhWA==' WHERE email = 'chemagtz85@gmail.com';
UPDATE auth.users SET encrypted_password = '$firebase$scrypt$v=1,p=C34xz4ekGPX5iZlzLDe+LmWIFePZi+7ncRYs4sgmucs=,s=Bw==,r=8,m=14$KAgFcUGnGF48Pw==$klDkT30SJ3+YGJSg8dXC9UbsCCCMQhSFA2aPvMZt7FgV1bY9POj+spfk2CzzzkqaHSfCjNohiq012cTGQUN2/Q==' WHERE email = 'sergio.checko.o@gmail.com';
UPDATE auth.users SET encrypted_password = '$firebase$scrypt$v=1,p=C34xz4ekGPX5iZlzLDe+LmWIFePZi+7ncRYs4sgmucs=,s=Bw==,r=8,m=14$S7iXndm5rrq9+Q==$l5YltJ6AA5Q3xLuxJCR0pdMkPJ9P07pN+z8WLqQT+dz7p11zPJgrWCbAbJusPcUWUt5Uf1t/Yip3/DTMyXbEig==' WHERE email = 'anetteguillenballinas@gmail.com';
UPDATE auth.users SET encrypted_password = '$firebase$scrypt$v=1,p=C34xz4ekGPX5iZlzLDe+LmWIFePZi+7ncRYs4sgmucs=,s=Bw==,r=8,m=14$Ebs31FGwIGiw1w==$stBCDId6yjf6aFdZEXDP17tmdFr2ZKGnCuyzS31Kv+E+y6BOodJ0aUcOrmhzzWU5wEYNiSNt0CbCLWy+kkJc0w==' WHERE email = 'trejo_yuri2912@hotmail.com';

COMMIT;
